project_id = "gurufoykncixameklolt"

[functions.case-correction-notify]
verify_jwt = false

[functions.send-notification]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.send-sms]
verify_jwt = false

[functions.sms-scheduler]
verify_jwt = false
